apiVersion: apps/v1
kind: Deployment
metadata:
  name: windfall-backend
  labels:
    app: windfall
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windfall
      tier: backend
  template:
    metadata:
      labels:
        app: windfall
        tier: backend
    spec:
      containers:
      - name: backend
        image: windfall-backend:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://windfall-mysql:3306/windfall?useSSL=false&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m -XX:+UseContainerSupport"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: windfall-backend
  labels:
    app: windfall
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: windfall
    tier: backend
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  username: d2luZGZhbGw=  # windfall (base64 encoded)
  password: d2luZGZhbGw=  # windfall (base64 encoded)
